CREATE DATABASE IF NOT EXISTS CAMPUS_QUICKACCESS DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI;

-- 创建学校表
DROP TABLE IF EXISTS QUICKACCESS_CUSTOMER;

CREATE TABLE QUICKACCESS_CUSTOMER (
        ID_ BIGINT NOT NULL,
        CREATEDATE_ DATETIME,
        CUSTOMERCODE_ VARCHAR(150),
        CUSTOMERID_ VARCHAR(255),
        CUSTOMERNAME_ VARCHAR(150),
        DPCODE_ VARCHAR(150),
        JIANPIN_ VARCHAR(255),
        PINYIN_ VARCHAR(255),
        SOURCEIPS_ VARCHAR(255),
        URL_ VARCHAR(200),
        PRIMARY KEY (ID_)
);

-- 创建学生表
DROP TABLE IF EXISTS QUICKACCESS_STUDENT;

CREATE TABLE QUICKACCESS_STUDENT (
        ID_ BIGINT NOT NULL,
        APPID_ VARCHAR(200),
        APPNAME_ VARCHAR(200),
        BINDCARDSTATE_ BIT,
        CUSTOMERCODE_ VARCHAR(255),
        CUSTOMERID_ VARCHAR(255),
        DATE_ DATETIME,
        NAME_ VARCHAR(255),
        OUTID_ VARCHAR(200),
        PARAM_ VARCHAR(2000),
        USERID_ VARCHAR(200),
        PRIMARY KEY (ID_)
 );